server:
  port: 8084
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
feign:
  okhttp:
    enabled: true

muy:
  swagger:
    title: 用户服务接口文档
    package: com.qingmuy.user.controller
  database:
    name: hm-user